# Annotation Framework

## ScriptoNet Digital Humanities Project

This notebook defines the annotation framework used to transform literary interpretation into structured data for Artificial Intelligence models.

The purpose of annotation is to create examples where literary passages are connected with meaningful categories that a machine learning model can learn from.

## Why Annotation Matters

A computer model cannot directly understand literary meaning.

For example:

A passage may contain:
- letters
- memories
- emotions
- suffering

However, these elements do not automatically indicate a therapeutic process.

Human interpretation is required to identify whether a passage represents:
- emotional processing
- healing
- reflection
- transformation

Annotation creates the bridge between literary analysis and machine learning.

## Annotation Task 1: Therapeutic Representation Detection

Each passage receives a binary label.

Label 1:
The passage contains a representation of emotional processing, reflection, healing, or transformation.

Label 0:
The passage does not contain a therapeutic representation.

This creates the first supervised learning task.

## Loading Computational Passages

The previous notebook transformed Frankenstein into 229 computational passages.

Each passage will now become a potential annotation unit.

The goal is to create additional fields that describe literary and therapeutic characteristics.

In [2]:
from google.colab import files

uploaded = files.upload()

Saving frankenstein_passages.csv to frankenstein_passages.csv

In [3]:
import pandas as pd

df = pd.read_csv("frankenstein_passages.csv")

df.head()

   passage_id                                               text
0           1  Frankenstein; or, the Modern Prometheus by Mar...
1           2  These reflections have dispelled the agitation...
2           3  Six years have passed since I resolved on my p...
3           4  This is the most favourable period for travell...
4           5  But I have one want which I have never yet bee...

## Current Dataset Structure

At this stage, the dataset only contains literary text.

The computer knows:

- passage number
- passage content

However, it does not know the literary meaning of each passage.

The next step is to create annotation fields that connect literary interpretation with machine learning.

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 229 entries, 0 to 228
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   passage_id  229 non-null    int64
 1   text        229 non-null    object
dtypes: int64(1), object(1)
memory usage: 3.7+ KB

In [5]:
df["therapeutic_label"] = None
df["mechanism"] = None
df["intensity"] = None
df["annotator_notes"] = None

df.head()

,passage_id,text,therapeutic_label,mechanism,intensity,annotator_notes
0,1,"Frankenstein; or, the Modern Prometheus by Mar...",None,None,None,None
1,2,These reflections have dispelled the agitation...,None,None,None,None
2,3,Six years have passed since I resolved on my p...,None,None,None,None
3,4,This is the most favourable period for travell...,None,None,None,None
4,5,But I have one want which I have never yet bee...,None,None,None,None

# Annotation Guidelines

Annotation guidelines define how literary passages will be labelled for machine learning.

The purpose is to ensure that human interpretation follows consistent rules before creating training data.

## Annotation Level 1: Therapeutic Representation

Question:

Does this passage represent a process of emotional processing, healing, reflection, or transformation?

Labels:

1 = Present

0 = Not Present


Label 1 examples:

- A character reflects on suffering and develops new understanding.
- Writing is used to process experiences.
- Emotional expression leads to transformation.


Label 0 examples:

- Physical descriptions
- Travel information
- Simple events without emotional processing
- Narrative background information

## Annotation Level 2: Therapeutic Mechanism

If the therapeutic representation is present, assign one category:

### 1. Scriptotherapy

Writing, letters, journals, confession, or storytelling used for emotional processing.


### 2. Poetry-mediated Processing

Poetry used for emotional expression or reflection.


### 3. Music-mediated Processing

Music used for emotional access, memory, or regulation.


### 4. Narrative Reconstruction

A character changes their understanding of themselves, their past, or their experiences.


### 5. Emotional Catharsis

Release or expression of previously contained emotions.

## Annotation Level 3: Intensity

Rate the strength of therapeutic representation.

1 = Very weak

2 = Weak

3 = Moderate

4 = Strong

5 = Very strong

## Pilot Annotation

Before creating the complete labelled dataset, a small sample of passages is selected for pilot annotation.

The purpose is to test whether the annotation guidelines are clear and whether literary interpretations can be converted into consistent labels.

In [6]:
# Select 10 random passages for pilot annotation

sample_df = df.sample(
    10,
    random_state=42
)

sample_df

,passage_id,text,therapeutic_label,mechanism,intensity,annotator_notes
216,217,"My beloved Sister, September 2d. I write to yo...",None,None,None,None
66,67,"“She most of all,” said Ernest, “requires cons...",None,None,None,None
9,10,This appearance excited our unqualified wonder...,None,None,None,None
192,193,Great God! If for one instant I had thought wh...,None,None,None,None
15,16,Will you smile at the enthusiasm I express con...,None,None,None,None
198,199,The report of the pistol brought a crowd into ...,None,None,None,None
25,26,I feel exquisite pleasure in dwelling on the r...,None,None,None,None
194,195,I took the hand of Elizabeth. “You are sorrowf...,None,None,None,None
154,155,But in Clerval I saw the image of my former se...,None,None,None,None
126,127,“I knocked. ‘Who is there?’ said the old man. ...,None,None,None,None

In [7]:
sample_df.to_csv(
    "frankenstein_annotation_pilot.csv",
    index=False
)

print("Pilot annotation file created")

Pilot annotation file created

In [8]:
sample_df[["passage_id", "text"]]

     passage_id                                               text
216         217  My beloved Sister, September 2d. I write to yo...
66           67  “She most of all,” said Ernest, “requires cons...
9            10  This appearance excited our unqualified wonder...
192         193  Great God! If for one instant I had thought wh...
15           16  Will you smile at the enthusiasm I express con...
198         199  The report of the pistol brought a crowd into ...
25           26  I feel exquisite pleasure in dwelling on the r...
194         195  I took the hand of Elizabeth. “You are sorrowf...
154         155  But in Clerval I saw the image of my former se...
126         127  “I knocked. ‘Who is there?’ said the old man. ...

## Example of Manual Annotation

Passage:

"The memories of my past filled me with sorrow, but I began to understand the events that shaped my life."

Annotation:

Therapeutic Label:
1

Mechanism:
Narrative Reconstruction

Intensity:
4

Reason:
The character is reflecting on past experiences and developing a changed understanding of personal events.

In [9]:

sample_df[["passage_id", "text"]]

     passage_id                                               text
216         217  My beloved Sister, September 2d. I write to yo...
66           67  “She most of all,” said Ernest, “requires cons...
9            10  This appearance excited our unqualified wonder...
192         193  Great God! If for one instant I had thought wh...
15           16  Will you smile at the enthusiasm I express con...
198         199  The report of the pistol brought a crowd into ...
25           26  I feel exquisite pleasure in dwelling on the r...
194         195  I took the hand of Elizabeth. “You are sorrowf...
154         155  But in Clerval I saw the image of my former se...
126         127  “I knocked. ‘Who is there?’ said the old man. ...

In [10]:
for pid in sample_df["passage_id"]:
    print("PASSAGE ID:", pid)
    print(df[df["passage_id"]==pid]["text"].values[0])
    print("\n"+"-"*80+"\n")

PASSAGE ID: 217
My beloved Sister, September 2d. I write to you, encompassed by peril and ignorant whether I am ever
doomed to see again dear England and the dearer friends that inhabit
it. I am surrounded by mountains of ice which admit of no escape and
threaten every moment to crush my vessel. The brave fellows whom I
have persuaded to be my companions look towards me for aid, but I have
none to bestow. There is something terribly appalling in our
situation, yet my courage and hopes do not desert me. Yet it is
terrible to reflect that the lives of all these men are endangered
through me. If we are lost, my mad schemes are the cause. And what, Margaret, will be the state of your mind? You will not hear of my
destruction, and you will anxiously await my return. Years will pass, and
you will have visitings of despair and yet be tortured by hope. Oh! My
beloved sister, the sickening failing of your heart-felt expectations is,
in prospect, more terrible to me than my own death. But you have a husband
and lovely children; you may be happy. Heaven bless you and make you so! My unfortunate guest regards me with the tenderest compassion. He
endeavours to fill me with hope and talks as if life were a possession
which he valued. He reminds me how often the same accidents have
happened to other navigators who have attempted this sea, and in spite
of myself, he fills me with cheerful auguries. Even the sailors feel
the power of his eloquence; when he speaks, they no longer despair; he
rouses their energies, and while they hear his voice they believe these
vast mountains of ice are mole-hills which will vanish before the
resolutions of man. These feelings are transitory; each day of
expectation delayed fills them with fear, and I almost dread a mutiny
caused by this despair.

--------------------------------------------------------------------------------

PASSAGE ID: 67
“She most of all,” said Ernest, “requires consolation; she accused
herself of having caused the death of my brother, and that made her
very wretched. But since the murderer has been discovered—” “The murderer discovered! Good God! how can that be? who could attempt
to pursue him? It is impossible; one might as well try to overtake the
winds, or confine a mountain-stream with a straw. I saw him too; he
was free last night!” “I do not know what you mean,” replied my brother, in accents of
wonder, “but to us the discovery we have made completes our misery. No
one would believe it at first; and even now Elizabeth will not be
convinced, notwithstanding all the evidence. Indeed, who would credit
that Justine Moritz, who was so amiable, and fond of all the family,
could suddenly become so capable of so frightful, so appalling a crime?” “Justine Moritz! Poor, poor girl, is she the accused? But it is
wrongfully; every one knows that; no one believes it, surely, Ernest?” “No one did at first; but several circumstances came out, that have
almost forced conviction upon us; and her own behaviour has been so
confused, as to add to the evidence of facts a weight that, I fear,
leaves no hope for doubt. But she will be tried today, and you will
then hear all.” He then related that, the morning on which the murder of poor William
had been discovered, Justine had been taken ill, and confined to her
bed for several days. During this interval, one of the servants,
happening to examine the apparel she had worn on the night of the
murder, had discovered in her pocket the picture of my mother, which
had been judged to be the temptation of the murderer. The servant
instantly showed it to one of the others, who, without saying a word to
any of the family, went to a magistrate; and, upon their deposition,
Justine was apprehended. On being charged with the fact, the poor girl
confirmed the suspicion in a great measure by her extreme confusion of
manner.

--------------------------------------------------------------------------------

PASSAGE ID: 10
This appearance excited our unqualified wonder. We were, as we believed,
many hundred miles from any land; but this apparition seemed to denote that
it was not, in reality, so distant as we had supposed. Shut in, however, by
ice, it was impossible to follow his track, which we had observed with the
greatest attention. About two hours after this occurrence we heard the ground sea, and before
night the ice broke and freed our ship. We, however, lay to until the
morning, fearing to encounter in the dark those large loose masses which
float about after the breaking up of the ice. I profited of this time to
rest for a few hours. In the morning, however, as soon as it was light, I went upon deck and
found all the sailors busy on one side of the vessel, apparently
talking to someone in the sea. It was, in fact, a sledge, like that we
had seen before, which had drifted towards us in the night on a large
fragment of ice. Only one dog remained alive; but there was a human
being within it whom the sailors were persuading to enter the vessel.
He was not, as the other traveller seemed to be, a savage inhabitant of
some undiscovered island, but a European. When I appeared on deck the
master said, “Here is our captain, and he will not allow you to perish
on the open sea.” On perceiving me, the stranger addressed me in English, although with a
foreign accent. “Before I come on board your vessel,” said he,
“will you have the kindness to inform me whither you are bound?”

--------------------------------------------------------------------------------

PASSAGE ID: 193
Great God! If for one instant I had thought what might be the hellish
intention of my fiendish adversary, I would rather have banished myself
for ever from my native country and wandered a friendless outcast over
the earth than have consented to this miserable marriage. But, as if
possessed of magic powers, the monster had blinded me to his real
intentions; and when I thought that I had prepared only my own death, I
hastened that of a far dearer victim. As the period fixed for our marriage drew nearer, whether from cowardice or
a prophetic feeling, I felt my heart sink within me. But I concealed my
feelings by an appearance of hilarity that brought smiles and joy to the
countenance of my father, but hardly deceived the ever-watchful and nicer
eye of Elizabeth. She looked forward to our union with placid contentment,
not unmingled with a little fear, which past misfortunes had impressed,
that what now appeared certain and tangible happiness might soon dissipate
into an airy dream and leave no trace but deep and everlasting regret. Preparations were made for the event, congratulatory visits were received,
and all wore a smiling appearance. I shut up, as well as I could, in my own
heart the anxiety that preyed there and entered with seeming earnestness
into the plans of my father, although they might only serve as the
decorations of my tragedy. Through my father’s exertions a part of
the inheritance of Elizabeth had been restored to her by the Austrian
government. A small possession on the shores of Como belonged to her. It
was agreed that, immediately after our union, we should proceed to Villa
Lavenza and spend our first days of happiness beside the beautiful lake
near which it stood.

--------------------------------------------------------------------------------

PASSAGE ID: 16
Will you smile at the enthusiasm I express concerning this divine
wanderer? You would not if you saw him. You have been tutored and
refined by books and retirement from the world, and you are therefore
somewhat fastidious; but this only renders you the more fit to
appreciate the extraordinary merits of this wonderful man. Sometimes I
have endeavoured to discover what quality it is which he possesses that
elevates him so immeasurably above any other person I ever knew. I
believe it to be an intuitive discernment, a quick but never-failing
power of judgment, a penetration into the causes of things, unequalled
for clearness and precision; add to this a facility of expression and a
voice whose varied intonations are soul-subduing music. August 19th, 17—. Yesterday the stranger said to me, “You may easily perceive, Captain
Walton, that I have suffered great and unparalleled misfortunes. I had
determined at one time that the memory of these evils should die with
me, but you have won me to alter my determination. You seek for
knowledge and wisdom, as I once did; and I ardently hope that the
gratification of your wishes may not be a serpent to sting you, as mine
has been. I do not know that the relation of my disasters will be
useful to you; yet, when I reflect that you are pursuing the same
course, exposing yourself to the same dangers which have rendered me
what I am, I imagine that you may deduce an apt moral from my tale, one
that may direct you if you succeed in your undertaking and console you
in case of failure. Prepare to hear of occurrences which are usually
deemed marvellous. Were we among the tamer scenes of nature I might
fear to encounter your unbelief, perhaps your ridicule; but many things
will appear possible in these wild and mysterious regions which would
provoke the laughter of those unacquainted with the ever-varied powers
of nature; nor can I doubt but that my tale conveys in its series
internal evidence of the truth of the events of which it is composed.”

--------------------------------------------------------------------------------

PASSAGE ID: 199
The report of the pistol brought a crowd into the room. I pointed to
the spot where he had disappeared, and we followed the track with
boats; nets were cast, but in vain. After passing several hours, we
returned hopeless, most of my companions believing it to have been a
form conjured up by my fancy. After having landed, they proceeded to
search the country, parties going in different directions among the
woods and vines. I attempted to accompany them and proceeded a short distance from the
house, but my head whirled round, my steps were like those of a drunken
man, I fell at last in a state of utter exhaustion; a film covered my
eyes, and my skin was parched with the heat of fever. In this state I
was carried back and placed on a bed, hardly conscious of what had
happened; my eyes wandered round the room as if to seek something that
I had lost. After an interval I arose, and as if by instinct, crawled into the room
where the corpse of my beloved lay. There were women weeping around; I
hung over it and joined my sad tears to theirs; all this time no
distinct idea presented itself to my mind, but my thoughts rambled to
various subjects, reflecting confusedly on my misfortunes and their
cause. I was bewildered, in a cloud of wonder and horror. The death
of William, the execution of Justine, the murder of Clerval, and lastly
of my wife; even at that moment I knew not that my only remaining
friends were safe from the malignity of the fiend; my father even now
might be writhing under his grasp, and Ernest might be dead at his
feet. This idea made me shudder and recalled me to action. I started
up and resolved to return to Geneva with all possible speed.

--------------------------------------------------------------------------------

PASSAGE ID: 26
I feel exquisite pleasure in dwelling on the recollections of childhood,
before misfortune had tainted my mind and changed its bright visions of
extensive usefulness into gloomy and narrow reflections upon self. Besides,
in drawing the picture of my early days, I also record those events which
led, by insensible steps, to my after tale of misery, for when I would
account to myself for the birth of that passion which afterwards ruled my
destiny I find it arise, like a mountain river, from ignoble and almost
forgotten sources; but, swelling as it proceeded, it became the torrent
which, in its course, has swept away all my hopes and joys. Natural philosophy is the genius that has regulated my fate; I desire,
therefore, in this narration, to state those facts which led to my
predilection for that science. When I was thirteen years of age we all went
on a party of pleasure to the baths near Thonon; the inclemency of the
weather obliged us to remain a day confined to the inn. In this house I
chanced to find a volume of the works of Cornelius Agrippa. I opened it
with apathy; the theory which he attempts to demonstrate and the wonderful
facts which he relates soon changed this feeling into enthusiasm. A new
light seemed to dawn upon my mind, and bounding with joy, I communicated my
discovery to my father. My father looked carelessly at the title page of my
book and said, “Ah! Cornelius Agrippa! My dear Victor, do not waste
your time upon this; it is sad trash.”

--------------------------------------------------------------------------------

PASSAGE ID: 195
I took the hand of Elizabeth. “You are sorrowful, my love. Ah! If
you knew what I have suffered and what I may yet endure, you would
endeavour to let me taste the quiet and freedom from despair that this
one day at least permits me to enjoy.” “Be happy, my dear Victor,” replied Elizabeth; “there is, I hope,
nothing to distress you; and be assured that if a lively joy is not
painted in my face, my heart is contented. Something whispers to me
not to depend too much on the prospect that is opened before us, but I
will not listen to such a sinister voice. Observe how fast we move
along and how the clouds, which sometimes obscure and sometimes rise
above the dome of Mont Blanc, render this scene of beauty still more
interesting. Look also at the innumerable fish that are swimming in
the clear waters, where we can distinguish every pebble that lies at
the bottom. What a divine day! How happy and serene all nature
appears!” Thus Elizabeth endeavoured to divert her thoughts and mine from all
reflection upon melancholy subjects. But her temper was fluctuating;
joy for a few instants shone in her eyes, but it continually gave place
to distraction and reverie. The sun sank lower in the heavens; we passed the river Drance and
observed its path through the chasms of the higher and the glens of the
lower hills. The Alps here come closer to the lake, and we approached
the amphitheatre of mountains which forms its eastern boundary. The
spire of Evian shone under the woods that surrounded it and the range
of mountain above mountain by which it was overhung.

--------------------------------------------------------------------------------

PASSAGE ID: 155
But in Clerval I saw the image of my former self; he was inquisitive
and anxious to gain experience and instruction. The difference of
manners which he observed was to him an inexhaustible source of
instruction and amusement. He was also pursuing an object he had long
had in view. His design was to visit India, in the belief that he had
in his knowledge of its various languages, and in the views he had
taken of its society, the means of materially assisting the progress of
European colonization and trade. In Britain only could he further the
execution of his plan. He was for ever busy, and the only check to his
enjoyments was my sorrowful and dejected mind. I tried to conceal this
as much as possible, that I might not debar him from the pleasures
natural to one who was entering on a new scene of life, undisturbed by
any care or bitter recollection. I often refused to accompany him,
alleging another engagement, that I might remain alone. I now also
began to collect the materials necessary for my new creation, and this
was to me like the torture of single drops of water continually falling
on the head. Every thought that was devoted to it was an extreme
anguish, and every word that I spoke in allusion to it caused my lips
to quiver, and my heart to palpitate. After passing some months in London, we received a letter from a person in
Scotland who had formerly been our visitor at Geneva. He mentioned the
beauties of his native country and asked us if those were not sufficient
allurements to induce us to prolong our journey as far north as Perth,
where he resided. Clerval eagerly desired to accept this invitation, and I,
although I abhorred society, wished to view again mountains and streams and
all the wondrous works with which Nature adorns her chosen dwelling-places.

--------------------------------------------------------------------------------

PASSAGE ID: 127
“I knocked. ‘Who is there?’ said the old man. ‘Come in.’ “I entered. ‘Pardon this intrusion,’ said I; ‘I am
a traveller in want of a little rest; you would greatly oblige me if you
would allow me to remain a few minutes before the fire.’ “‘Enter,’ said De Lacey, ‘and I will try in what
manner I can to relieve your wants; but, unfortunately, my children are
from home, and as I am blind, I am afraid I shall find it difficult to
procure food for you.’ “‘Do not trouble yourself, my kind host; I have food; it is
warmth and rest only that I need.’ “I sat down, and a silence ensued. I knew that every minute was
precious to me, yet I remained irresolute in what manner to commence
the interview, when the old man addressed me. ‘By your language, stranger, I suppose you are my countryman; are you
French?’ “‘No; but I was educated by a French family and understand that
language only. I am now going to claim the protection of some friends,
whom I sincerely love, and of whose favour I have some hopes.’ “‘Are they Germans?’ “‘No, they are French. But let us change the subject. I am an
unfortunate and deserted creature, I look around and I have no relation
or friend upon earth. These amiable people to whom I go have never
seen me and know little of me. I am full of fears, for if I fail
there, I am an outcast in the world for ever.’

--------------------------------------------------------------------------------

In [11]:
df.loc[df["passage_id"] == 217, "therapeutic_label"] = 1
df.loc[df["passage_id"] == 217, "mechanism"] = "Emotional Catharsis"
df.loc[df["passage_id"] == 217, "intensity"] = 3
df.loc[df["passage_id"] == 217, "annotator_notes"] = "The passage represents emotional distress, self-reflection, and compassionate support. Walton experiences guilt and fear while receiving hope and reassurance."

In [12]:
df[df["passage_id"] == 217]

,passage_id,text,therapeutic_label,mechanism,intensity,annotator_notes
216,217,"My beloved Sister, September 2d. I write to yo...",1,Emotional Catharsis,3,"The passage represents emotional distress, sel..."

In [13]:
df[df["passage_id"] == 67]["text"].values[0]

'“She most of all,” said Ernest, “requires consolation; she accused\nherself of having caused the death of my brother, and that made her\nvery wretched. But since the murderer has been discovered—” “The murderer discovered! Good God! how can that be? who could attempt\nto pursue him? It is impossible; one might as well try to overtake the\nwinds, or confine a mountain-stream with a straw. I saw him too; he\nwas free last night!” “I do not know what you mean,” replied my brother, in accents of\nwonder, “but to us the discovery we have made completes our misery. No\none would believe it at first; and even now Elizabeth will not be\nconvinced, notwithstanding all the evidence. Indeed, who would credit\nthat Justine Moritz, who was so amiable, and fond of all the family,\ncould suddenly become so capable of so frightful, so appalling a crime?” “Justine Moritz! Poor, poor girl, is she the accused? But it is\nwrongfully; every one knows that; no one believes it, surely, Ernest?” “No one did at first; but several circumstances came out, that have\nalmost forced conviction upon us; and her own behaviour has been so\nconfused, as to add to the evidence of facts a weight that, I fear,\nleaves no hope for doubt. But she will be tried today, and you will\nthen hear all.” He then related that, the morning on which the murder of poor William\nhad been discovered, Justine had been taken ill, and confined to her\nbed for several days. During this interval, one of the servants,\nhappening to examine the apparel she had worn on the night of the\nmurder, had discovered in her pocket the picture of my mother, which\nhad been judged to be the temptation of the murderer. The servant\ninstantly showed it to one of the others, who, without saying a word to\nany of the family, went to a magistrate; and, upon their deposition,\nJustine was apprehended. On being charged with the fact, the poor girl\nconfirmed the suspicion in a great measure by her extreme confusion of\nmanner.'

In [14]:
df.loc[df["passage_id"] == 67, "therapeutic_label"] = 0

df.loc[df["passage_id"] == 67, "mechanism"] = "None"

df.loc[df["passage_id"] == 67, "intensity"] = 0

df.loc[df["passage_id"] == 67, "annotator_notes"] = "The passage describes grief, guilt, and emotional suffering after William's death. However, it represents the experience of trauma rather than a therapeutic process of reflection, healing, or transformation."

In [15]:
df[df["passage_id"] == 67]

,passage_id,text,therapeutic_label,mechanism,intensity,annotator_notes
66,67,"“She most of all,” said Ernest, “requires cons...",0,None,0,"The passage describes grief, guilt, and emotio..."

In [16]:
df[df["passage_id"] == 10]["text"].values[0]

'This appearance excited our unqualified wonder. We were, as we believed,\nmany hundred miles from any land; but this apparition seemed to denote that\nit was not, in reality, so distant as we had supposed. Shut in, however, by\nice, it was impossible to follow his track, which we had observed with the\ngreatest attention. About two hours after this occurrence we heard the ground sea, and before\nnight the ice broke and freed our ship. We, however, lay to until the\nmorning, fearing to encounter in the dark those large loose masses which\nfloat about after the breaking up of the ice. I profited of this time to\nrest for a few hours. In the morning, however, as soon as it was light, I went upon deck and\nfound all the sailors busy on one side of the vessel, apparently\ntalking to someone in the sea. It was, in fact, a sledge, like that we\nhad seen before, which had drifted towards us in the night on a large\nfragment of ice. Only one dog remained alive; but there was a human\nbeing within it whom the sailors were persuading to enter the vessel.\nHe was not, as the other traveller seemed to be, a savage inhabitant of\nsome undiscovered island, but a European. When I appeared on deck the\nmaster said, “Here is our captain, and he will not allow you to perish\non the open sea.” On perceiving me, the stranger addressed me in English, although with a\nforeign accent. “Before I come on board your vessel,” said he,\n“will you have the kindness to inform me whither you are bound?”'

In [17]:
df.loc[df["passage_id"] == 10, "therapeutic_label"] = 0

df.loc[df["passage_id"] == 10, "mechanism"] = "None"

df.loc[df["passage_id"] == 10, "intensity"] = 0

df.loc[df["passage_id"] == 10, "annotator_notes"] = "The passage describes curiosity and wonder during an unusual event in Walton's expedition. Although emotional reactions are present, the passage does not represent emotional processing, healing, or transformation."

In [18]:
df[df["passage_id"] == 10]

,passage_id,text,therapeutic_label,mechanism,intensity,annotator_notes
9,10,This appearance excited our unqualified wonder...,0,None,0,The passage describes curiosity and wonder dur...

In [19]:
df[df["passage_id"] == 193]["text"].values[0]

'Great God! If for one instant I had thought what might be the hellish\nintention of my fiendish adversary, I would rather have banished myself\nfor ever from my native country and wandered a friendless outcast over\nthe earth than have consented to this miserable marriage. But, as if\npossessed of magic powers, the monster had blinded me to his real\nintentions; and when I thought that I had prepared only my own death, I\nhastened that of a far dearer victim. As the period fixed for our marriage drew nearer, whether from cowardice or\na prophetic feeling, I felt my heart sink within me. But I concealed my\nfeelings by an appearance of hilarity that brought smiles and joy to the\ncountenance of my father, but hardly deceived the ever-watchful and nicer\neye of Elizabeth. She looked forward to our union with placid contentment,\nnot unmingled with a little fear, which past misfortunes had impressed,\nthat what now appeared certain and tangible happiness might soon dissipate\ninto an airy dream and leave no trace but deep and everlasting regret. Preparations were made for the event, congratulatory visits were received,\nand all wore a smiling appearance. I shut up, as well as I could, in my own\nheart the anxiety that preyed there and entered with seeming earnestness\ninto the plans of my father, although they might only serve as the\ndecorations of my tragedy. Through my father’s exertions a part of\nthe inheritance of Elizabeth had been restored to her by the Austrian\ngovernment. A small possession on the shores of Como belonged to her. It\nwas agreed that, immediately after our union, we should proceed to Villa\nLavenza and spend our first days of happiness beside the beautiful lake\nnear which it stood.'

In [20]:
df.loc[df["passage_id"] == 193, "therapeutic_label"] = 0

df.loc[df["passage_id"] == 193, "mechanism"] = "None"

df.loc[df["passage_id"] == 193, "intensity"] = 0

df.loc[df["passage_id"] == 193, "annotator_notes"] = "The passage represents intense guilt, fear, and regret following traumatic events. Although Victor reflects on his past actions, the passage presents psychological suffering rather than a process of healing, emotional processing, or transformation."

In [21]:
df[df["passage_id"] == 193]

,passage_id,text,therapeutic_label,mechanism,intensity,annotator_notes
192,193,Great God! If for one instant I had thought wh...,0,None,0,"The passage represents intense guilt, fear, an..."

In [22]:
df[df["passage_id"] == 16]["text"].values[0]

'Will you smile at the enthusiasm I express concerning this divine\nwanderer? You would not if you saw him. You have been tutored and\nrefined by books and retirement from the world, and you are therefore\nsomewhat fastidious; but this only renders you the more fit to\nappreciate the extraordinary merits of this wonderful man. Sometimes I\nhave endeavoured to discover what quality it is which he possesses that\nelevates him so immeasurably above any other person I ever knew. I\nbelieve it to be an intuitive discernment, a quick but never-failing\npower of judgment, a penetration into the causes of things, unequalled\nfor clearness and precision; add to this a facility of expression and a\nvoice whose varied intonations are soul-subduing music. August 19th, 17—. Yesterday the stranger said to me, “You may easily perceive, Captain\nWalton, that I have suffered great and unparalleled misfortunes. I had\ndetermined at one time that the memory of these evils should die with\nme, but you have won me to alter my determination. You seek for\nknowledge and wisdom, as I once did; and I ardently hope that the\ngratification of your wishes may not be a serpent to sting you, as mine\nhas been. I do not know that the relation of my disasters will be\nuseful to you; yet, when I reflect that you are pursuing the same\ncourse, exposing yourself to the same dangers which have rendered me\nwhat I am, I imagine that you may deduce an apt moral from my tale, one\nthat may direct you if you succeed in your undertaking and console you\nin case of failure. Prepare to hear of occurrences which are usually\ndeemed marvellous. Were we among the tamer scenes of nature I might\nfear to encounter your unbelief, perhaps your ridicule; but many things\nwill appear possible in these wild and mysterious regions which would\nprovoke the laughter of those unacquainted with the ever-varied powers\nof nature; nor can I doubt but that my tale conveys in its series\ninternal evidence of the truth of the events of which it is composed.”'

In [23]:
df.loc[df["passage_id"] == 16, "therapeutic_label"] = 1

df.loc[df["passage_id"] == 16, "mechanism"] = "Narrative Reconstruction"

df.loc[df["passage_id"] == 16, "intensity"] = 3

df.loc[df["passage_id"] == 16, "annotator_notes"] = "The passage introduces Victor's suffering and his decision to share painful memories with Walton. The act of narrating past experiences represents an early stage of emotional processing and narrative reconstruction, although complete healing or transformation is not yet shown."

In [24]:
df[df["passage_id"] == 16]

,passage_id,text,therapeutic_label,mechanism,intensity,annotator_notes
15,16,Will you smile at the enthusiasm I express con...,1,Narrative Reconstruction,3,The passage introduces Victor's suffering and ...

In [25]:
df[df["passage_id"] == 199]["text"].values[0]

'The report of the pistol brought a crowd into the room. I pointed to\nthe spot where he had disappeared, and we followed the track with\nboats; nets were cast, but in vain. After passing several hours, we\nreturned hopeless, most of my companions believing it to have been a\nform conjured up by my fancy. After having landed, they proceeded to\nsearch the country, parties going in different directions among the\nwoods and vines. I attempted to accompany them and proceeded a short distance from the\nhouse, but my head whirled round, my steps were like those of a drunken\nman, I fell at last in a state of utter exhaustion; a film covered my\neyes, and my skin was parched with the heat of fever. In this state I\nwas carried back and placed on a bed, hardly conscious of what had\nhappened; my eyes wandered round the room as if to seek something that\nI had lost. After an interval I arose, and as if by instinct, crawled into the room\nwhere the corpse of my beloved lay. There were women weeping around; I\nhung over it and joined my sad tears to theirs; all this time no\ndistinct idea presented itself to my mind, but my thoughts rambled to\nvarious subjects, reflecting confusedly on my misfortunes and their\ncause. I was bewildered, in a cloud of wonder and horror. The death\nof William, the execution of Justine, the murder of Clerval, and lastly\nof my wife; even at that moment I knew not that my only remaining\nfriends were safe from the malignity of the fiend; my father even now\nmight be writhing under his grasp, and Ernest might be dead at his\nfeet. This idea made me shudder and recalled me to action. I started\nup and resolved to return to Geneva with all possible speed.'

In [26]:
df.loc[df["passage_id"] == 199, "therapeutic_label"] = 0

df.loc[df["passage_id"] == 199, "mechanism"] = "None"

df.loc[df["passage_id"] == 199, "intensity"] = 0

df.loc[df["passage_id"] == 199, "annotator_notes"] = "The passage represents intense physical and emotional trauma following a violent loss. Although grief and suffering are strongly expressed, the passage depicts immediate traumatic response rather than emotional processing, healing, or transformation."

In [27]:
df[df["passage_id"] == 199]

,passage_id,text,therapeutic_label,mechanism,intensity,annotator_notes
198,199,The report of the pistol brought a crowd into ...,0,None,0,The passage represents intense physical and em...

In [28]:
df[df["passage_id"] == 26]["text"].values[0]

'I feel exquisite pleasure in dwelling on the recollections of childhood,\nbefore misfortune had tainted my mind and changed its bright visions of\nextensive usefulness into gloomy and narrow reflections upon self. Besides,\nin drawing the picture of my early days, I also record those events which\nled, by insensible steps, to my after tale of misery, for when I would\naccount to myself for the birth of that passion which afterwards ruled my\ndestiny I find it arise, like a mountain river, from ignoble and almost\nforgotten sources; but, swelling as it proceeded, it became the torrent\nwhich, in its course, has swept away all my hopes and joys. Natural philosophy is the genius that has regulated my fate; I desire,\ntherefore, in this narration, to state those facts which led to my\npredilection for that science. When I was thirteen years of age we all went\non a party of pleasure to the baths near Thonon; the inclemency of the\nweather obliged us to remain a day confined to the inn. In this house I\nchanced to find a volume of the works of Cornelius Agrippa. I opened it\nwith apathy; the theory which he attempts to demonstrate and the wonderful\nfacts which he relates soon changed this feeling into enthusiasm. A new\nlight seemed to dawn upon my mind, and bounding with joy, I communicated my\ndiscovery to my father. My father looked carelessly at the title page of my\nbook and said, “Ah! Cornelius Agrippa! My dear Victor, do not waste\nyour time upon this; it is sad trash.”'

In [29]:
df.loc[df["passage_id"] == 26, "therapeutic_label"] = 1

df.loc[df["passage_id"] == 26, "mechanism"] = "Narrative Reconstruction"

df.loc[df["passage_id"] == 26, "intensity"] = 4

df.loc[df["passage_id"] == 26, "annotator_notes"] = "The passage represents autobiographical reflection and narrative reconstruction. Victor revisits childhood memories and attempts to understand how earlier experiences shaped his later suffering and identity. The passage demonstrates meaning-making through storytelling rather than simple recollection."

In [30]:
df[df["passage_id"] == 26]

,passage_id,text,therapeutic_label,mechanism,intensity,annotator_notes
25,26,I feel exquisite pleasure in dwelling on the r...,1,Narrative Reconstruction,4,The passage represents autobiographical reflec...

In [31]:
df[df["passage_id"] == 195]["text"].values[0]

'I took the hand of Elizabeth. “You are sorrowful, my love. Ah! If\nyou knew what I have suffered and what I may yet endure, you would\nendeavour to let me taste the quiet and freedom from despair that this\none day at least permits me to enjoy.” “Be happy, my dear Victor,” replied Elizabeth; “there is, I hope,\nnothing to distress you; and be assured that if a lively joy is not\npainted in my face, my heart is contented. Something whispers to me\nnot to depend too much on the prospect that is opened before us, but I\nwill not listen to such a sinister voice. Observe how fast we move\nalong and how the clouds, which sometimes obscure and sometimes rise\nabove the dome of Mont Blanc, render this scene of beauty still more\ninteresting. Look also at the innumerable fish that are swimming in\nthe clear waters, where we can distinguish every pebble that lies at\nthe bottom. What a divine day! How happy and serene all nature\nappears!” Thus Elizabeth endeavoured to divert her thoughts and mine from all\nreflection upon melancholy subjects. But her temper was fluctuating;\njoy for a few instants shone in her eyes, but it continually gave place\nto distraction and reverie. The sun sank lower in the heavens; we passed the river Drance and\nobserved its path through the chasms of the higher and the glens of the\nlower hills. The Alps here come closer to the lake, and we approached\nthe amphitheatre of mountains which forms its eastern boundary. The\nspire of Evian shone under the woods that surrounded it and the range\nof mountain above mountain by which it was overhung.'

In [32]:
df.loc[df["passage_id"] == 195, "therapeutic_label"] = 1

df.loc[df["passage_id"] == 195, "mechanism"] = "Emotional Catharsis"

df.loc[df["passage_id"] == 195, "intensity"] = 3

df.loc[df["passage_id"] == 195, "annotator_notes"] = "The passage represents emotional disclosure and interpersonal support. Victor expresses his hidden suffering, while Elizabeth attempts to provide comfort and emotional reassurance. The interaction represents a moderate therapeutic process through emotional connection rather than complete transformation."

In [33]:
df[df["passage_id"] == 195]

,passage_id,text,therapeutic_label,mechanism,intensity,annotator_notes
194,195,I took the hand of Elizabeth. “You are sorrowf...,1,Emotional Catharsis,3,The passage represents emotional disclosure an...

In [34]:
df[df["passage_id"] == 155]["text"].values[0]

'But in Clerval I saw the image of my former self; he was inquisitive\nand anxious to gain experience and instruction. The difference of\nmanners which he observed was to him an inexhaustible source of\ninstruction and amusement. He was also pursuing an object he had long\nhad in view. His design was to visit India, in the belief that he had\nin his knowledge of its various languages, and in the views he had\ntaken of its society, the means of materially assisting the progress of\nEuropean colonization and trade. In Britain only could he further the\nexecution of his plan. He was for ever busy, and the only check to his\nenjoyments was my sorrowful and dejected mind. I tried to conceal this\nas much as possible, that I might not debar him from the pleasures\nnatural to one who was entering on a new scene of life, undisturbed by\nany care or bitter recollection. I often refused to accompany him,\nalleging another engagement, that I might remain alone. I now also\nbegan to collect the materials necessary for my new creation, and this\nwas to me like the torture of single drops of water continually falling\non the head. Every thought that was devoted to it was an extreme\nanguish, and every word that I spoke in allusion to it caused my lips\nto quiver, and my heart to palpitate. After passing some months in London, we received a letter from a person in\nScotland who had formerly been our visitor at Geneva. He mentioned the\nbeauties of his native country and asked us if those were not sufficient\nallurements to induce us to prolong our journey as far north as Perth,\nwhere he resided. Clerval eagerly desired to accept this invitation, and I,\nalthough I abhorred society, wished to view again mountains and streams and\nall the wondrous works with which Nature adorns her chosen dwelling-places.'

In [35]:
df.loc[df["passage_id"] == 155, "therapeutic_label"] = 1

df.loc[df["passage_id"] == 155, "mechanism"] = "Narrative Reconstruction"

df.loc[df["passage_id"] == 155, "intensity"] = 3

df.loc[df["passage_id"] == 155, "annotator_notes"] = "The passage represents narrative reconstruction through interpersonal reflection. Victor views Clerval as a reflection of his former identity and recognises the contrast between his previous self and his current sorrowful state. The passage shows self-understanding, although healing is not yet achieved."

In [36]:
df[df["passage_id"] == 155]

,passage_id,text,therapeutic_label,mechanism,intensity,annotator_notes
154,155,But in Clerval I saw the image of my former se...,1,Narrative Reconstruction,3,The passage represents narrative reconstructio...

In [37]:
df[df["passage_id"] == 127]["text"].values[0]

'“I knocked. ‘Who is there?’ said the old man. ‘Come in.’ “I entered. ‘Pardon this intrusion,’ said I; ‘I am\na traveller in want of a little rest; you would greatly oblige me if you\nwould allow me to remain a few minutes before the fire.’ “‘Enter,’ said De Lacey, ‘and I will try in what\nmanner I can to relieve your wants; but, unfortunately, my children are\nfrom home, and as I am blind, I am afraid I shall find it difficult to\nprocure food for you.’ “‘Do not trouble yourself, my kind host; I have food; it is\nwarmth and rest only that I need.’ “I sat down, and a silence ensued. I knew that every minute was\nprecious to me, yet I remained irresolute in what manner to commence\nthe interview, when the old man addressed me. ‘By your language, stranger, I suppose you are my countryman; are you\nFrench?’ “‘No; but I was educated by a French family and understand that\nlanguage only. I am now going to claim the protection of some friends,\nwhom I sincerely love, and of whose favour I have some hopes.’ “‘Are they Germans?’ “‘No, they are French. But let us change the subject. I am an\nunfortunate and deserted creature, I look around and I have no relation\nor friend upon earth. These amiable people to whom I go have never\nseen me and know little of me. I am full of fears, for if I fail\nthere, I am an outcast in the world for ever.’'

In [38]:
df.loc[df["passage_id"] == 127, "therapeutic_label"] = 0

df.loc[df["passage_id"] == 127, "mechanism"] = "None"

df.loc[df["passage_id"] == 127, "intensity"] = 0

df.loc[df["passage_id"] == 127, "annotator_notes"] = "The passage represents a compassionate social interaction between the Creature and De Lacey. Although kindness and human connection are present, the passage does not show emotional processing, healing, or transformation."

In [39]:
df[df["passage_id"] == 127]

,passage_id,text,therapeutic_label,mechanism,intensity,annotator_notes
126,127,“I knocked. ‘Who is there?’ said the old man. ...,0,None,0,The passage represents a compassionate social ...

In [40]:
df.to_csv(
    "frankenstein_annotated_pilot.csv",
    index=False
)

print("Annotated pilot dataset saved successfully")

Annotated pilot dataset saved successfully

In [41]:
from google.colab import files

files.download("frankenstein_annotated_pilot.csv")