# Baseline Machine Learning Model

## Objective

The purpose of this notebook is to establish a baseline computational model that learns from human-annotated literary passages.

The model will investigate whether textual features can predict therapeutic representations in literary narratives.

## Dataset Preparation

Machine learning requires separating available data into training and testing sets.

The training set is used by the model to learn patterns from annotated literary passages.

The testing set evaluates whether the model can generalize its learning to unseen passages.

In [1]:
import pandas as pd

from sklearn.model_selection import train_test_split

print("Libraries loaded successfully")

Libraries loaded successfully

In [2]:
from google.colab import files

uploaded = files.upload()

Saving frankenstein_annotated_pilot.csv to frankenstein_annotated_pilot.csv

In [3]:
df = pd.read_csv("frankenstein_annotated_pilot.csv")

df.head()

,passage_id,text,therapeutic_label,mechanism,intensity,annotator_notes
0,1,"Frankenstein; or, the Modern Prometheus by Mar...",NaN,NaN,NaN,NaN
1,2,These reflections have dispelled the agitation...,NaN,NaN,NaN,NaN
2,3,Six years have passed since I resolved on my p...,NaN,NaN,NaN,NaN
3,4,This is the most favourable period for travell...,NaN,NaN,NaN,NaN
4,5,But I have one want which I have never yet bee...,NaN,NaN,NaN,NaN

In [4]:
df[df["passage_id"].isin([217,67,10,193,16,199,26,195,155,127])]

,passage_id,text,therapeutic_label,mechanism,intensity,annotator_notes
9,10,This appearance excited our unqualified wonder...,0.0,NaN,0.0,The passage describes curiosity and wonder dur...
15,16,Will you smile at the enthusiasm I express con...,1.0,Narrative Reconstruction,3.0,The passage introduces Victor's suffering and ...
25,26,I feel exquisite pleasure in dwelling on the r...,1.0,Narrative Reconstruction,4.0,The passage represents autobiographical reflec...
66,67,"“She most of all,” said Ernest, “requires cons...",0.0,NaN,0.0,"The passage describes grief, guilt, and emotio..."
126,127,“I knocked. ‘Who is there?’ said the old man. ...,0.0,NaN,0.0,The passage represents a compassionate social ...
154,155,But in Clerval I saw the image of my former se...,1.0,Narrative Reconstruction,3.0,The passage represents narrative reconstructio...
192,193,Great God! If for one instant I had thought wh...,0.0,NaN,0.0,"The passage represents intense guilt, fear, an..."
194,195,I took the hand of Elizabeth. “You are sorrowf...,1.0,Emotional Catharsis,3.0,The passage represents emotional disclosure an...
198,199,The report of the pistol brought a crowd into ...,0.0,NaN,0.0,The passage represents intense physical and em...
216,217,"My beloved Sister, September 2d. I write to yo...",1.0,Emotional Catharsis,3.0,"The passage represents emotional distress, sel..."

## Separating Features and Labels

The literary text acts as the input feature, while the human annotation serves as the prediction target.

The objective is to train a model that learns whether a passage represents a therapeutic process based on textual patterns.

In [5]:
X = df["text"]
y = df["therapeutic_label"]

print("Input examples:")
print(X.head())

print("\nLabels:")
print(y.head())

Input examples:
0    Frankenstein; or, the Modern Prometheus by Mar...
1    These reflections have dispelled the agitation...
2    Six years have passed since I resolved on my p...
3    This is the most favourable period for travell...
4    But I have one want which I have never yet bee...
Name: text, dtype: object

Labels:
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: therapeutic_label, dtype: float64

In [6]:
# Keep only passages with human annotations

ml_df = df.dropna(subset=["therapeutic_label"])

print("Dataset size:", len(ml_df))

ml_df.head()

Dataset size: 10

,passage_id,text,therapeutic_label,mechanism,intensity,annotator_notes
9,10,This appearance excited our unqualified wonder...,0.0,NaN,0.0,The passage describes curiosity and wonder dur...
15,16,Will you smile at the enthusiasm I express con...,1.0,Narrative Reconstruction,3.0,The passage introduces Victor's suffering and ...
25,26,I feel exquisite pleasure in dwelling on the r...,1.0,Narrative Reconstruction,4.0,The passage represents autobiographical reflec...
66,67,"“She most of all,” said Ernest, “requires cons...",0.0,NaN,0.0,"The passage describes grief, guilt, and emotio..."
126,127,“I knocked. ‘Who is there?’ said the old man. ...,0.0,NaN,0.0,The passage represents a compassionate social ...

In [7]:
X = ml_df["text"]
y = ml_df["therapeutic_label"]

print("Input examples:")
print(X.head())

print("\nLabels:")
print(y.head())

Input examples:
9      This appearance excited our unqualified wonder...
15     Will you smile at the enthusiasm I express con...
25     I feel exquisite pleasure in dwelling on the r...
66     “She most of all,” said Ernest, “requires cons...
126    “I knocked. ‘Who is there?’ said the old man. ...
Name: text, dtype: object

Labels:
9      0.0
15     1.0
25     1.0
66     0.0
126    0.0
Name: therapeutic_label, dtype: float64

## Train-Test Split

The dataset is divided into training and testing subsets.

The training data is used to teach the machine learning model patterns from annotated literary passages.

The testing data is kept unseen and is used to evaluate whether the model can generalize its learning.

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

Training samples: 8
Testing samples: 2

## Text Feature Extraction using TF-IDF

Machine learning algorithms cannot directly process raw literary text.

TF-IDF converts textual passages into numerical representations by measuring the importance of words within the dataset.

These numerical features allow machine learning models to identify patterns associated with therapeutic representations.

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()

X_train_tfidf = tfidf.fit_transform(X_train)

X_test_tfidf = tfidf.transform(X_test)

print("Training feature shape:", X_train_tfidf.shape)
print("Testing feature shape:", X_test_tfidf.shape)

Training feature shape: (8, 897)
Testing feature shape: (2, 897)

## Baseline Classification Model

A Logistic Regression classifier is used as the first baseline model.

The objective is to test whether textual features extracted using TF-IDF can predict whether a passage represents a therapeutic process.

In [10]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(
    X_train_tfidf,
    y_train
)

print("Model trained successfully")

Model trained successfully

In [11]:
predictions = model.predict(X_test_tfidf)

print(predictions)

[1. 1.]

In [12]:
print("Predicted:", predictions)

print("Actual:", y_test.values)

Predicted: [1. 1.]
Actual: [0. 1.]

In [13]:
results = pd.DataFrame({
    "text": X_test,
    "actual": y_test,
    "predicted": predictions
})

results

                                                  text  actual  predicted
198  The report of the pistol brought a crowd into ...     0.0        1.0
15   Will you smile at the enthusiasm I express con...     1.0        1.0

## Baseline Model Evaluation

The trained model is evaluated using standard classification metrics.

These metrics measure how accurately the model predicts therapeutic representations in unseen literary passages.

In [14]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

accuracy = accuracy_score(
    y_test,
    predictions
)

print("Accuracy:", accuracy)


print("\nConfusion Matrix:")
print(confusion_matrix(y_test, predictions))


print("\nClassification Report:")
print(classification_report(y_test, predictions))

Accuracy: 0.5

Confusion Matrix:
[[0 1]
 [0 1]]

Classification Report:
              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00         1
         1.0       0.50      1.00      0.67         1

    accuracy                           0.50         2
   macro avg       0.25      0.50      0.33         2
weighted avg       0.25      0.50      0.33         2

/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

## Baseline Model Findings

The initial TF-IDF Logistic Regression model was evaluated on unseen literary passages.

The model achieved 50% accuracy. Error analysis revealed that the model confused emotional suffering with therapeutic representation, demonstrating the limitations of surface-level textual features.