# Annotation Expansion Batch 02

## Objective

This notebook expands the human-annotated Frankenstein dataset by identifying additional passages with potential therapeutic representations.

The selected passages will be manually evaluated using the established annotation framework:

- therapeutic_label
- mechanism
- intensity
- annotator_notes

In [1]:
import pandas as pd
import numpy as np

print("Libraries loaded successfully")

Libraries loaded successfully

In [2]:
from google.colab import files

uploaded = files.upload()

Saving frankenstein_passages.csv to frankenstein_passages.csv

In [3]:
passages_df = pd.read_csv(
    "frankenstein_passages.csv"
)

print("Dataset loaded")
print("Total passages:", len(passages_df))

passages_df.head()

Dataset loaded
Total passages: 229

   passage_id                                               text
0           1  Frankenstein; or, the Modern Prometheus by Mar...
1           2  These reflections have dispelled the agitation...
2           3  Six years have passed since I resolved on my p...
3           4  This is the most favourable period for travell...
4           5  But I have one want which I have never yet bee...

In [5]:
from google.colab import files

uploaded = files.upload()

Saving frankenstein_training_dataset.csv to frankenstein_training_dataset.csv

In [6]:
annotated_df = pd.read_csv(
    "frankenstein_training_dataset.csv"
)

print("Existing annotated passages:", len(annotated_df))

annotated_df.head()

Existing annotated passages: 29

,passage_id,text,therapeutic_label,mechanism,intensity,annotator_notes,keyword_score
0,10,This appearance excited our unqualified wonder...,0.0,NaN,0.0,The passage describes curiosity and wonder dur...,NaN
1,16,Will you smile at the enthusiasm I express con...,1.0,Narrative Reconstruction,3.0,The passage introduces Victor's suffering and ...,NaN
2,26,I feel exquisite pleasure in dwelling on the r...,1.0,Narrative Reconstruction,4.0,The passage represents autobiographical reflec...,NaN
3,67,"“She most of all,” said Ernest, “requires cons...",0.0,NaN,0.0,"The passage describes grief, guilt, and emotio...",NaN
4,127,“I knocked. ‘Who is there?’ said the old man. ...,0.0,NaN,0.0,The passage represents a compassionate social ...,NaN

In [7]:
remaining_df = passages_df[
    ~passages_df["passage_id"].isin(
        annotated_df["passage_id"]
    )
]

print("Remaining passages:", len(remaining_df))

remaining_df.head()

Remaining passages: 200

   passage_id                                               text
0           1  Frankenstein; or, the Modern Prometheus by Mar...
1           2  These reflections have dispelled the agitation...
2           3  Six years have passed since I resolved on my p...
3           4  This is the most favourable period for travell...
4           5  But I have one want which I have never yet bee...

## Candidate Selection Strategy

Remaining passages are ranked using emotional and reflective linguistic indicators.

The scoring system identifies passages containing potential therapeutic elements such as:

- emotional expression
- memory and reflection
- interpersonal support
- acceptance
- transformation

In [8]:
therapeutic_keywords = [
    "memory",
    "remember",
    "reflection",
    "reflect",
    "feel",
    "feeling",
    "heart",
    "mind",
    "sorrow",
    "grief",
    "hope",
    "comfort",
    "friend",
    "sympathy",
    "love",
    "affection",
    "forgive",
    "forgiveness",
    "peace",
    "happiness",
    "joy",
    "understand",
    "learn",
    "accept",
    "calm",
    "consolation",
    "support"
]

print("Keyword list created")

Keyword list created

In [9]:
def keyword_score(text):
    text = text.lower()

    score = 0

    for word in therapeutic_keywords:
        if word in text:
            score += 1

    return score


remaining_df["keyword_score"] = remaining_df["text"].apply(
    keyword_score
)

remaining_df.head()

/tmp/ipykernel_499/3134510840.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  remaining_df["keyword_score"] = remaining_df["text"].apply(

,passage_id,text,keyword_score
0,1,"Frankenstein; or, the Modern Prometheus by Mar...",5
1,2,These reflections have dispelled the agitation...,7
2,3,Six years have passed since I resolved on my p...,2
3,4,This is the most favourable period for travell...,2
4,5,But I have one want which I have never yet bee...,6

In [10]:
candidate_df = remaining_df.sort_values(
    by="keyword_score",
    ascending=False
)

candidate_df[
    ["passage_id", "keyword_score", "text"]
].head(20)

,passage_id,keyword_score,text
61,62,10,Clerval spoke thus as we hurried through the s...
122,123,10,“The volume of _Plutarch’s Lives_ which I poss...
184,185,10,"Still, as I urged our leaving Ireland with suc..."
42,43,9,The summer months passed while I was thus enga...
113,114,9,“I cannot describe to you the agony that these...
152,153,9,Clerval! Beloved friend! Even now it delights ...
59,60,9,"“He was conveyed home, and the anguish that wa..."
213,214,9,His tale is connected and told with an appeara...
221,222,9,“Yet I cannot ask you to renounce your country...
214,215,9,Our conversations are not always confined to h...
107,108,8,"“My thoughts now became more active, and I lon..."
104,105,8,“By degrees I made a discovery of still greate...
193,194,8,In the meantime I took every precaution to def...
159,160,8,I visited Edinburgh with languid eyes and mind...
224,225,8,“After the murder of Clerval I returned to Swi...
219,220,8,He spoke this with a voice so modulated to the...
18,19,8,Beaufort had taken effectual measures to conce...
109,110,8,“Felix seemed ravished with delight when he sa...
143,144,8,His words had a strange effect upon me. I comp...
60,61,8,"“Your affectionate and afflicted father, “Alph..."

In [11]:
batch02_candidates = candidate_df[
    candidate_df["passage_id"].isin(
        [62,123,185,43,114,153,60,214,222,215]
    )
]

batch02_candidates[
    ["passage_id","keyword_score","text"]
]

,passage_id,keyword_score,text
61,62,10,Clerval spoke thus as we hurried through the s...
122,123,10,“The volume of _Plutarch’s Lives_ which I poss...
184,185,10,"Still, as I urged our leaving Ireland with suc..."
42,43,9,The summer months passed while I was thus enga...
113,114,9,“I cannot describe to you the agony that these...
152,153,9,Clerval! Beloved friend! Even now it delights ...
59,60,9,"“He was conveyed home, and the anguish that wa..."
213,214,9,His tale is connected and told with an appeara...
221,222,9,“Yet I cannot ask you to renounce your country...
214,215,9,Our conversations are not always confined to h...

In [12]:
batch02_ids = [62,123,185,43,114,153,60,214,222,215]

batch02_texts = candidate_df[
    candidate_df["passage_id"].isin(batch02_ids)
]

for _, row in batch02_texts.iterrows():
    print("\n" + "="*80)
    print("PASSAGE ID:", row["passage_id"])
    print("KEYWORD SCORE:", row["keyword_score"])
    print("\n", row["text"])

================================================================================
PASSAGE ID: 62
KEYWORD SCORE: 10

 Clerval spoke thus as we hurried through the streets; the words
impressed themselves on my mind and I remembered them afterwards in
solitude. But now, as soon as the horses arrived, I hurried into a
cabriolet, and bade farewell to my friend. My journey was very melancholy. At first I wished to hurry on, for I longed
to console and sympathise with my loved and sorrowing friends; but when I
drew near my native town, I slackened my progress. I could hardly sustain
the multitude of feelings that crowded into my mind. I passed through
scenes familiar to my youth, but which I had not seen for nearly six years.
How altered every thing might be during that time! One sudden and
desolating change had taken place; but a thousand little circumstances
might have by degrees worked other alterations, which, although they were
done more tranquilly, might not be the less decisive. Fear overcame me; I
dared no advance, dreading a thousand nameless evils that made me tremble,
although I was unable to define them. I remained two days at Lausanne, in this painful state of mind. I
contemplated the lake: the waters were placid; all around was calm; and the
snowy mountains, “the palaces of nature,” were not changed. By
degrees the calm and heavenly scene restored me, and I continued my journey
towards Geneva. The road ran by the side of the lake, which became narrower as I
approached my native town. I discovered more distinctly the black
sides of Jura, and the bright summit of Mont Blanc. I wept like a
child. “Dear mountains! my own beautiful lake! how do you welcome your
wanderer? Your summits are clear; the sky and lake are blue and
placid. Is this to prognosticate peace, or to mock at my unhappiness?”

================================================================================
PASSAGE ID: 123
KEYWORD SCORE: 10

 “The volume of _Plutarch’s Lives_ which I possessed contained the
histories of the first founders of the ancient republics. This book
had a far different effect upon me from the _Sorrows of Werter_. I
learned from Werter’s imaginations despondency and gloom, but Plutarch
taught me high thoughts; he elevated me above the wretched sphere of my
own reflections, to admire and love the heroes of past ages. Many
things I read surpassed my understanding and experience. I had a very
confused knowledge of kingdoms, wide extents of country, mighty rivers,
and boundless seas. But I was perfectly unacquainted with towns and
large assemblages of men. The cottage of my protectors had been the
only school in which I had studied human nature, but this book
developed new and mightier scenes of action. I read of men concerned
in public affairs, governing or massacring their species. I felt the
greatest ardour for virtue rise within me, and abhorrence for vice, as
far as I understood the signification of those terms, relative as they
were, as I applied them, to pleasure and pain alone. Induced by these
feelings, I was of course led to admire peaceable lawgivers, Numa,
Solon, and Lycurgus, in preference to Romulus and Theseus. The
patriarchal lives of my protectors caused these impressions to take a
firm hold on my mind; perhaps, if my first introduction to humanity had
been made by a young soldier, burning for glory and slaughter, I should
have been imbued with different sensations. “But _Paradise Lost_ excited different and far deeper emotions. I read
it, as I had read the other volumes which had fallen into my hands, as
a true history. It moved every feeling of wonder and awe that the
picture of an omnipotent God warring with his creatures was capable of
exciting. I often referred the several situations, as their similarity
struck me, to my own. Like Adam, I was apparently united by no link to
any other being in existence; but his state was far different from mine
in every other respect. He had come forth from the hands of God a
perfect creature, happy and prosperous, guarded by the especial care of
his Creator; he was allowed to converse with and acquire knowledge from
beings of a superior nature, but I was wretched, helpless, and alone.
Many times I considered Satan as the fitter emblem of my condition, for
often, like him, when I viewed the bliss of my protectors, the bitter
gall of envy rose within me.

================================================================================
PASSAGE ID: 185
KEYWORD SCORE: 10

 Still, as I urged our leaving Ireland with such inquietude and impatience,
my father thought it best to yield. We took our passage on board a vessel
bound for Havre-de-Grace and sailed with a fair wind from the Irish shores.
It was midnight. I lay on the deck looking at the stars and listening to
the dashing of the waves. I hailed the darkness that shut Ireland from my
sight, and my pulse beat with a feverish joy when I reflected that I should
soon see Geneva. The past appeared to me in the light of a frightful dream;
yet the vessel in which I was, the wind that blew me from the detested
shore of Ireland, and the sea which surrounded me, told me too forcibly
that I was deceived by no vision and that Clerval, my friend and dearest
companion, had fallen a victim to me and the monster of my creation. I
repassed, in my memory, my whole life; my quiet happiness while residing
with my family in Geneva, the death of my mother, and my departure for
Ingolstadt. I remembered, shuddering, the mad enthusiasm that hurried me on
to the creation of my hideous enemy, and I called to mind the night in
which he first lived. I was unable to pursue the train of thought; a
thousand feelings pressed upon me, and I wept bitterly. Ever since my recovery from the fever, I had been in the custom of taking
every night a small quantity of laudanum, for it was by means of this drug
only that I was enabled to gain the rest necessary for the preservation of
life. Oppressed by the recollection of my various misfortunes, I now
swallowed double my usual quantity and soon slept profoundly. But sleep did
not afford me respite from thought and misery; my dreams presented a
thousand objects that scared me. Towards morning I was possessed by a kind
of nightmare; I felt the fiend’s grasp in my neck and could not free
myself from it; groans and cries rang in my ears. My father, who was
watching over me, perceiving my restlessness, awoke me; the dashing waves
were around, the cloudy sky above, the fiend was not here: a sense of
security, a feeling that a truce was established between the present hour
and the irresistible, disastrous future imparted to me a kind of calm
forgetfulness, of which the human mind is by its structure peculiarly
susceptible.

================================================================================
PASSAGE ID: 43
KEYWORD SCORE: 9

 The summer months passed while I was thus engaged, heart and soul, in
one pursuit. It was a most beautiful season; never did the fields
bestow a more plentiful harvest or the vines yield a more luxuriant
vintage, but my eyes were insensible to the charms of nature. And the
same feelings which made me neglect the scenes around me caused me also
to forget those friends who were so many miles absent, and whom I had
not seen for so long a time. I knew my silence disquieted them, and I
well remembered the words of my father: “I know that while you are
pleased with yourself you will think of us with affection, and we shall
hear regularly from you. You must pardon me if I regard any
interruption in your correspondence as a proof that your other duties
are equally neglected.” I knew well therefore what would be my father’s feelings, but I could
not tear my thoughts from my employment, loathsome in itself, but which
had taken an irresistible hold of my imagination. I wished, as it
were, to procrastinate all that related to my feelings of affection
until the great object, which swallowed up every habit of my nature,
should be completed. I then thought that my father would be unjust if he ascribed my neglect
to vice or faultiness on my part, but I am now convinced that he was
justified in conceiving that I should not be altogether free from
blame. A human being in perfection ought always to preserve a calm and
peaceful mind and never to allow passion or a transitory desire to
disturb his tranquillity. I do not think that the pursuit of knowledge
is an exception to this rule. If the study to which you apply yourself
has a tendency to weaken your affections and to destroy your taste for
those simple pleasures in which no alloy can possibly mix, then that
study is certainly unlawful, that is to say, not befitting the human
mind. If this rule were always observed; if no man allowed any pursuit
whatsoever to interfere with the tranquillity of his domestic
affections, Greece had not been enslaved, Cæsar would have spared his
country, America would have been discovered more gradually, and the
empires of Mexico and Peru had not been destroyed.

================================================================================
PASSAGE ID: 114
KEYWORD SCORE: 9

 “I cannot describe to you the agony that these reflections inflicted
upon me; I tried to dispel them, but sorrow only increased with
knowledge. Oh, that I had for ever remained in my native wood, nor
known nor felt beyond the sensations of hunger, thirst, and heat! “Of what a strange nature is knowledge! It clings to the mind when it
has once seized on it like a lichen on the rock. I wished sometimes to
shake off all thought and feeling, but I learned that there was but one
means to overcome the sensation of pain, and that was death—a state
which I feared yet did not understand. I admired virtue and good
feelings and loved the gentle manners and amiable qualities of my
cottagers, but I was shut out from intercourse with them, except
through means which I obtained by stealth, when I was unseen and
unknown, and which rather increased than satisfied the desire I had of
becoming one among my fellows. The gentle words of Agatha and the
animated smiles of the charming Arabian were not for me. The mild
exhortations of the old man and the lively conversation of the loved
Felix were not for me. Miserable, unhappy wretch! “Other lessons were impressed upon me even more deeply. I heard of the
difference of sexes, and the birth and growth of children, how the
father doted on the smiles of the infant, and the lively sallies of the
older child, how all the life and cares of the mother were wrapped up
in the precious charge, how the mind of youth expanded and gained
knowledge, of brother, sister, and all the various relationships which
bind one human being to another in mutual bonds.

================================================================================
PASSAGE ID: 153
KEYWORD SCORE: 9

 Clerval! Beloved friend! Even now it delights me to record your words and
to dwell on the praise of which you are so eminently deserving. He was a
being formed in the “very poetry of nature.” His wild and
enthusiastic imagination was chastened by the sensibility of his heart. His
soul overflowed with ardent affections, and his friendship was of that
devoted and wondrous nature that the worldly-minded teach us to look for only
in the imagination. But even human sympathies were not sufficient to
satisfy his eager mind. The scenery of external nature, which others regard
only with admiration, he loved with ardour:— ——The sounding cataract
    Haunted him like a passion: the tall rock,
    The mountain, and the deep and gloomy wood,
    Their colours and their forms, were then to him
    An appetite; a feeling, and a love,
    That had no need of a remoter charm,
    By thought supplied, or any interest
    Unborrow’d from the eye. [Wordsworth’s “Tintern Abbey”.] And where does he now exist? Is this gentle and lovely being lost
for ever? Has this mind, so replete with ideas, imaginations fanciful
and magnificent, which formed a world, whose existence depended on the
life of its creator;—has this mind perished? Does it now only exist
in my memory? No, it is not thus; your form so divinely wrought, and
beaming with beauty, has decayed, but your spirit still visits and
consoles your unhappy friend. Pardon this gush of sorrow; these ineffectual words are but a slight
tribute to the unexampled worth of Henry, but they soothe my heart,
overflowing with the anguish which his remembrance creates. I will
proceed with my tale.

================================================================================
PASSAGE ID: 60
KEYWORD SCORE: 9

 “He was conveyed home, and the anguish that was visible in my
countenance betrayed the secret to Elizabeth. She was very earnest to
see the corpse. At first I attempted to prevent her but she persisted,
and entering the room where it lay, hastily examined the neck of the
victim, and clasping her hands exclaimed, ‘O God! I have murdered my
darling child!’ “She fainted, and was restored with extreme difficulty. When she again
lived, it was only to weep and sigh. She told me, that that same
evening William had teased her to let him wear a very valuable
miniature that she possessed of your mother. This picture is gone, and
was doubtless the temptation which urged the murderer to the deed. We
have no trace of him at present, although our exertions to discover him
are unremitted; but they will not restore my beloved William! “Come, dearest Victor; you alone can console Elizabeth. She weeps
continually, and accuses herself unjustly as the cause of his death;
her words pierce my heart. We are all unhappy; but will not that be an
additional motive for you, my son, to return and be our comforter?
Your dear mother! Alas, Victor! I now say, Thank God she did not live
to witness the cruel, miserable death of her youngest darling! “Come, Victor; not brooding thoughts of vengeance against the assassin,
but with feelings of peace and gentleness, that will heal, instead of
festering, the wounds of our minds. Enter the house of mourning, my
friend, but with kindness and affection for those who love you, and not
with hatred for your enemies.

================================================================================
PASSAGE ID: 214
KEYWORD SCORE: 9

 His tale is connected and told with an appearance of the simplest truth,
yet I own to you that the letters of Felix and Safie, which he showed me,
and the apparition of the monster seen from our ship, brought to me a
greater conviction of the truth of his narrative than his asseverations,
however earnest and connected. Such a monster has, then, really existence!
I cannot doubt it, yet I am lost in surprise and admiration. Sometimes I
endeavoured to gain from Frankenstein the particulars of his
creature’s formation, but on this point he was impenetrable. “Are you mad, my friend?” said he. “Or whither does your
senseless curiosity lead you? Would you also create for yourself and the
world a demoniacal enemy? Peace, peace! Learn my miseries and do not seek
to increase your own.” Frankenstein discovered that I made notes concerning his history; he asked
to see them and then himself corrected and augmented them in many places,
but principally in giving the life and spirit to the conversations he held
with his enemy. “Since you have preserved my narration,” said
he, “I would not that a mutilated one should go down to
posterity.” Thus has a week passed away, while I have listened to the strangest
tale that ever imagination formed. My thoughts and every feeling of my
soul have been drunk up by the interest for my guest which this tale
and his own elevated and gentle manners have created. I wish to soothe
him, yet can I counsel one so infinitely miserable, so destitute of
every hope of consolation, to live? Oh, no! The only joy that he can
now know will be when he composes his shattered spirit to peace and
death. Yet he enjoys one comfort, the offspring of solitude and
delirium; he believes that when in dreams he holds converse with his
friends and derives from that communion consolation for his miseries or
excitements to his vengeance, that they are not the creations of his
fancy, but the beings themselves who visit him from the regions of a
remote world. This faith gives a solemnity to his reveries that render
them to me almost as imposing and interesting as truth.

================================================================================
PASSAGE ID: 222
KEYWORD SCORE: 9

 “Yet I cannot ask you to renounce your country and friends to fulfil
this task; and now that you are returning to England, you will have
little chance of meeting with him. But the consideration of these
points, and the well balancing of what you may esteem your duties, I
leave to you; my judgment and ideas are already disturbed by the near
approach of death. I dare not ask you to do what I think right, for I
may still be misled by passion. “That he should live to be an instrument of mischief disturbs me; in
other respects, this hour, when I momentarily expect my release, is the
only happy one which I have enjoyed for several years. The forms of
the beloved dead flit before me, and I hasten to their arms. Farewell,
Walton! Seek happiness in tranquillity and avoid ambition, even if it
be only the apparently innocent one of distinguishing yourself in
science and discoveries. Yet why do I say this? I have myself been
blasted in these hopes, yet another may succeed.” His voice became fainter as he spoke, and at length, exhausted by his
effort, he sank into silence. About half an hour afterwards he
attempted again to speak but was unable; he pressed my hand feebly, and
his eyes closed for ever, while the irradiation of a gentle smile passed
away from his lips. Margaret, what comment can I make on the untimely extinction of this
glorious spirit? What can I say that will enable you to understand the
depth of my sorrow? All that I should express would be inadequate and
feeble. My tears flow; my mind is overshadowed by a cloud of
disappointment. But I journey towards England, and I may there find
consolation.

================================================================================
PASSAGE ID: 215
KEYWORD SCORE: 9

 Our conversations are not always confined to his own history and
misfortunes. On every point of general literature he displays
unbounded knowledge and a quick and piercing apprehension. His
eloquence is forcible and touching; nor can I hear him, when he relates
a pathetic incident or endeavours to move the passions of pity or love,
without tears. What a glorious creature must he have been in the days
of his prosperity, when he is thus noble and godlike in ruin! He seems
to feel his own worth and the greatness of his fall. “When younger,” said he, “I believed myself destined for
some great enterprise. My feelings are profound, but I possessed a coolness
of judgment that fitted me for illustrious achievements. This sentiment of
the worth of my nature supported me when others would have been oppressed,
for I deemed it criminal to throw away in useless grief those talents that
might be useful to my fellow creatures. When I reflected on the work I had
completed, no less a one than the creation of a sensitive and rational
animal, I could not rank myself with the herd of common projectors. But
this thought, which supported me in the commencement of my career, now
serves only to plunge me lower in the dust. All my speculations and hopes
are as nothing, and like the archangel who aspired to omnipotence, I am
chained in an eternal hell. My imagination was vivid, yet my powers of
analysis and application were intense; by the union of these qualities I
conceived the idea and executed the creation of a man. Even now I cannot
recollect without passion my reveries while the work was incomplete. I trod
heaven in my thoughts, now exulting in my powers, now burning with the idea
of their effects. From my infancy I was imbued with high hopes and a lofty

In [13]:
batch02_annotations = pd.DataFrame(
    columns=[
        "passage_id",
        "therapeutic_label",
        "mechanism",
        "intensity",
        "annotator_notes"
    ]
)

print("Batch 02 annotation table created")

Batch 02 annotation table created

In [14]:
batch02_annotations.loc[len(batch02_annotations)] = [
    62,
    1,
    "Narrative Reconstruction",
    3,
    "The passage represents emotional reflection and narrative reconstruction as Victor revisits familiar landscapes from his childhood and processes changes in his life. Although the passage contains fear and grief, interaction with memory and nature provides gradual emotional restoration and meaning-making."
]

batch02_annotations

,passage_id,therapeutic_label,mechanism,intensity,annotator_notes
0,62,1,Narrative Reconstruction,3,The passage represents emotional reflection an...

In [15]:
passage_id = 123

candidate_df[
    candidate_df["passage_id"] == passage_id
]["text"].values[0]

'“The volume of _Plutarch’s Lives_ which I possessed contained the\nhistories of the first founders of the ancient republics. This book\nhad a far different effect upon me from the _Sorrows of Werter_. I\nlearned from Werter’s imaginations despondency and gloom, but Plutarch\ntaught me high thoughts; he elevated me above the wretched sphere of my\nown reflections, to admire and love the heroes of past ages. Many\nthings I read surpassed my understanding and experience. I had a very\nconfused knowledge of kingdoms, wide extents of country, mighty rivers,\nand boundless seas. But I was perfectly unacquainted with towns and\nlarge assemblages of men. The cottage of my protectors had been the\nonly school in which I had studied human nature, but this book\ndeveloped new and mightier scenes of action. I read of men concerned\nin public affairs, governing or massacring their species. I felt the\ngreatest ardour for virtue rise within me, and abhorrence for vice, as\nfar as I understood the signification of those terms, relative as they\nwere, as I applied them, to pleasure and pain alone. Induced by these\nfeelings, I was of course led to admire peaceable lawgivers, Numa,\nSolon, and Lycurgus, in preference to Romulus and Theseus. The\npatriarchal lives of my protectors caused these impressions to take a\nfirm hold on my mind; perhaps, if my first introduction to humanity had\nbeen made by a young soldier, burning for glory and slaughter, I should\nhave been imbued with different sensations. “But _Paradise Lost_ excited different and far deeper emotions. I read\nit, as I had read the other volumes which had fallen into my hands, as\na true history. It moved every feeling of wonder and awe that the\npicture of an omnipotent God warring with his creatures was capable of\nexciting. I often referred the several situations, as their similarity\nstruck me, to my own. Like Adam, I was apparently united by no link to\nany other being in existence; but his state was far different from mine\nin every other respect. He had come forth from the hands of God a\nperfect creature, happy and prosperous, guarded by the especial care of\nhis Creator; he was allowed to converse with and acquire knowledge from\nbeings of a superior nature, but I was wretched, helpless, and alone.\nMany times I considered Satan as the fitter emblem of my condition, for\noften, like him, when I viewed the bliss of my protectors, the bitter\ngall of envy rose within me.'

In [16]:
batch02_annotations.loc[len(batch02_annotations)] = [
    123,
    1,
    "Narrative Reconstruction",
    4,
    "The passage represents narrative reconstruction through self-education and moral reflection. The creature describes how literature transforms his understanding of humanity, virtue, and his own identity. The movement from despair toward higher thoughts demonstrates a strong process of psychological and intellectual development."
]

batch02_annotations

,passage_id,therapeutic_label,mechanism,intensity,annotator_notes
0,62,1,Narrative Reconstruction,3,The passage represents emotional reflection an...
1,123,1,Narrative Reconstruction,4,The passage represents narrative reconstructio...

In [17]:
passage_id = 185

candidate_df[
    candidate_df["passage_id"] == passage_id
]["text"].values[0]

'Still, as I urged our leaving Ireland with such inquietude and impatience,\nmy father thought it best to yield. We took our passage on board a vessel\nbound for Havre-de-Grace and sailed with a fair wind from the Irish shores.\nIt was midnight. I lay on the deck looking at the stars and listening to\nthe dashing of the waves. I hailed the darkness that shut Ireland from my\nsight, and my pulse beat with a feverish joy when I reflected that I should\nsoon see Geneva. The past appeared to me in the light of a frightful dream;\nyet the vessel in which I was, the wind that blew me from the detested\nshore of Ireland, and the sea which surrounded me, told me too forcibly\nthat I was deceived by no vision and that Clerval, my friend and dearest\ncompanion, had fallen a victim to me and the monster of my creation. I\nrepassed, in my memory, my whole life; my quiet happiness while residing\nwith my family in Geneva, the death of my mother, and my departure for\nIngolstadt. I remembered, shuddering, the mad enthusiasm that hurried me on\nto the creation of my hideous enemy, and I called to mind the night in\nwhich he first lived. I was unable to pursue the train of thought; a\nthousand feelings pressed upon me, and I wept bitterly. Ever since my recovery from the fever, I had been in the custom of taking\nevery night a small quantity of laudanum, for it was by means of this drug\nonly that I was enabled to gain the rest necessary for the preservation of\nlife. Oppressed by the recollection of my various misfortunes, I now\nswallowed double my usual quantity and soon slept profoundly. But sleep did\nnot afford me respite from thought and misery; my dreams presented a\nthousand objects that scared me. Towards morning I was possessed by a kind\nof nightmare; I felt the fiend’s grasp in my neck and could not free\nmyself from it; groans and cries rang in my ears. My father, who was\nwatching over me, perceiving my restlessness, awoke me; the dashing waves\nwere around, the cloudy sky above, the fiend was not here: a sense of\nsecurity, a feeling that a truce was established between the present hour\nand the irresistible, disastrous future imparted to me a kind of calm\nforgetfulness, of which the human mind is by its structure peculiarly\nsusceptible.'

In [18]:
batch02_annotations.loc[len(batch02_annotations)] = [
    185,
    1,
    "Narrative Reconstruction",
    3,
    "The passage represents narrative reconstruction through Victor's recollection of significant life events, including family memories, loss, and personal responsibility. Although dominated by guilt and suffering, the act of reviewing his life history reflects an attempt to process trauma and understand his experiences."
]

batch02_annotations

,passage_id,therapeutic_label,mechanism,intensity,annotator_notes
0,62,1,Narrative Reconstruction,3,The passage represents emotional reflection an...
1,123,1,Narrative Reconstruction,4,The passage represents narrative reconstructio...
2,185,1,Narrative Reconstruction,3,The passage represents narrative reconstructio...

In [19]:
passage_id = 43

candidate_df[
    candidate_df["passage_id"] == passage_id
]["text"].values[0]

'The summer months passed while I was thus engaged, heart and soul, in\none pursuit. It was a most beautiful season; never did the fields\nbestow a more plentiful harvest or the vines yield a more luxuriant\nvintage, but my eyes were insensible to the charms of nature. And the\nsame feelings which made me neglect the scenes around me caused me also\nto forget those friends who were so many miles absent, and whom I had\nnot seen for so long a time. I knew my silence disquieted them, and I\nwell remembered the words of my father: “I know that while you are\npleased with yourself you will think of us with affection, and we shall\nhear regularly from you. You must pardon me if I regard any\ninterruption in your correspondence as a proof that your other duties\nare equally neglected.” I knew well therefore what would be my father’s feelings, but I could\nnot tear my thoughts from my employment, loathsome in itself, but which\nhad taken an irresistible hold of my imagination. I wished, as it\nwere, to procrastinate all that related to my feelings of affection\nuntil the great object, which swallowed up every habit of my nature,\nshould be completed. I then thought that my father would be unjust if he ascribed my neglect\nto vice or faultiness on my part, but I am now convinced that he was\njustified in conceiving that I should not be altogether free from\nblame. A human being in perfection ought always to preserve a calm and\npeaceful mind and never to allow passion or a transitory desire to\ndisturb his tranquillity. I do not think that the pursuit of knowledge\nis an exception to this rule. If the study to which you apply yourself\nhas a tendency to weaken your affections and to destroy your taste for\nthose simple pleasures in which no alloy can possibly mix, then that\nstudy is certainly unlawful, that is to say, not befitting the human\nmind. If this rule were always observed; if no man allowed any pursuit\nwhatsoever to interfere with the tranquillity of his domestic\naffections, Greece had not been enslaved, Cæsar would have spared his\ncountry, America would have been discovered more gradually, and the\nempires of Mexico and Peru had not been destroyed.'

In [20]:
batch02_annotations.loc[len(batch02_annotations)] = [
    43,
    0,
    "None",
    0,
    "The passage describes Victor's obsessive scientific pursuit and emotional isolation rather than a therapeutic process. Although he remembers his family and recognizes their concern, the passage focuses on withdrawal, neglect of relationships, and loss of connection."
]

batch02_annotations

,passage_id,therapeutic_label,mechanism,intensity,annotator_notes
0,62,1,Narrative Reconstruction,3,The passage represents emotional reflection an...
1,123,1,Narrative Reconstruction,4,The passage represents narrative reconstructio...
2,185,1,Narrative Reconstruction,3,The passage represents narrative reconstructio...
3,43,0,None,0,The passage describes Victor's obsessive scien...

In [21]:
passage_id = 114

candidate_df[
    candidate_df["passage_id"] == passage_id
]["text"].values[0]

'“I cannot describe to you the agony that these reflections inflicted\nupon me; I tried to dispel them, but sorrow only increased with\nknowledge. Oh, that I had for ever remained in my native wood, nor\nknown nor felt beyond the sensations of hunger, thirst, and heat! “Of what a strange nature is knowledge! It clings to the mind when it\nhas once seized on it like a lichen on the rock. I wished sometimes to\nshake off all thought and feeling, but I learned that there was but one\nmeans to overcome the sensation of pain, and that was death—a state\nwhich I feared yet did not understand. I admired virtue and good\nfeelings and loved the gentle manners and amiable qualities of my\ncottagers, but I was shut out from intercourse with them, except\nthrough means which I obtained by stealth, when I was unseen and\nunknown, and which rather increased than satisfied the desire I had of\nbecoming one among my fellows. The gentle words of Agatha and the\nanimated smiles of the charming Arabian were not for me. The mild\nexhortations of the old man and the lively conversation of the loved\nFelix were not for me. Miserable, unhappy wretch! “Other lessons were impressed upon me even more deeply. I heard of the\ndifference of sexes, and the birth and growth of children, how the\nfather doted on the smiles of the infant, and the lively sallies of the\nolder child, how all the life and cares of the mother were wrapped up\nin the precious charge, how the mind of youth expanded and gained\nknowledge, of brother, sister, and all the various relationships which\nbind one human being to another in mutual bonds.'

In [22]:
batch02_annotations.loc[len(batch02_annotations)] = [
    114,
    1,
    "Narrative Reconstruction",
    3,
    "The passage represents narrative reconstruction through deep reflection on knowledge, suffering, identity, and social isolation. The speaker examines how experience has shaped his understanding of himself and his desire for connection, although the emotional state remains painful."
]

batch02_annotations

,passage_id,therapeutic_label,mechanism,intensity,annotator_notes
0,62,1,Narrative Reconstruction,3,The passage represents emotional reflection an...
1,123,1,Narrative Reconstruction,4,The passage represents narrative reconstructio...
2,185,1,Narrative Reconstruction,3,The passage represents narrative reconstructio...
3,43,0,None,0,The passage describes Victor's obsessive scien...
4,114,1,Narrative Reconstruction,3,The passage represents narrative reconstructio...

In [23]:
passage_id = 153

candidate_df[
    candidate_df["passage_id"] == passage_id
]["text"].values[0]

'Clerval! Beloved friend! Even now it delights me to record your words and\nto dwell on the praise of which you are so eminently deserving. He was a\nbeing formed in the “very poetry of nature.” His wild and\nenthusiastic imagination was chastened by the sensibility of his heart. His\nsoul overflowed with ardent affections, and his friendship was of that\ndevoted and wondrous nature that the worldly-minded teach us to look for only\nin the imagination. But even human sympathies were not sufficient to\nsatisfy his eager mind. The scenery of external nature, which others regard\nonly with admiration, he loved with ardour:— ——The sounding cataract\n    Haunted him like a passion: the tall rock,\n    The mountain, and the deep and gloomy wood,\n    Their colours and their forms, were then to him\n    An appetite; a feeling, and a love,\n    That had no need of a remoter charm,\n    By thought supplied, or any interest\n    Unborrow’d from the eye. [Wordsworth’s “Tintern Abbey”.] And where does he now exist? Is this gentle and lovely being lost\nfor ever? Has this mind, so replete with ideas, imaginations fanciful\nand magnificent, which formed a world, whose existence depended on the\nlife of its creator;—has this mind perished? Does it now only exist\nin my memory? No, it is not thus; your form so divinely wrought, and\nbeaming with beauty, has decayed, but your spirit still visits and\nconsoles your unhappy friend. Pardon this gush of sorrow; these ineffectual words are but a slight\ntribute to the unexampled worth of Henry, but they soothe my heart,\noverflowing with the anguish which his remembrance creates. I will\nproceed with my tale.'

In [24]:
batch02_annotations.loc[len(batch02_annotations)] = [
    153,
    1,
    "Emotional Catharsis",
    4,
    "The passage represents emotional catharsis through Victor's remembrance and appreciation of Clerval. By expressing admiration, affection, and the emotional significance of friendship, the passage transforms grief into a reflective acknowledgement of human connection."
]

batch02_annotations

,passage_id,therapeutic_label,mechanism,intensity,annotator_notes
0,62,1,Narrative Reconstruction,3,The passage represents emotional reflection an...
1,123,1,Narrative Reconstruction,4,The passage represents narrative reconstructio...
2,185,1,Narrative Reconstruction,3,The passage represents narrative reconstructio...
3,43,0,None,0,The passage describes Victor's obsessive scien...
4,114,1,Narrative Reconstruction,3,The passage represents narrative reconstructio...
5,153,1,Emotional Catharsis,4,The passage represents emotional catharsis thr...

In [25]:
passage_id = 60

candidate_df[
    candidate_df["passage_id"] == passage_id
]["text"].values[0]

'“He was conveyed home, and the anguish that was visible in my\ncountenance betrayed the secret to Elizabeth. She was very earnest to\nsee the corpse. At first I attempted to prevent her but she persisted,\nand entering the room where it lay, hastily examined the neck of the\nvictim, and clasping her hands exclaimed, ‘O God! I have murdered my\ndarling child!’ “She fainted, and was restored with extreme difficulty. When she again\nlived, it was only to weep and sigh. She told me, that that same\nevening William had teased her to let him wear a very valuable\nminiature that she possessed of your mother. This picture is gone, and\nwas doubtless the temptation which urged the murderer to the deed. We\nhave no trace of him at present, although our exertions to discover him\nare unremitted; but they will not restore my beloved William! “Come, dearest Victor; you alone can console Elizabeth. She weeps\ncontinually, and accuses herself unjustly as the cause of his death;\nher words pierce my heart. We are all unhappy; but will not that be an\nadditional motive for you, my son, to return and be our comforter?\nYour dear mother! Alas, Victor! I now say, Thank God she did not live\nto witness the cruel, miserable death of her youngest darling! “Come, Victor; not brooding thoughts of vengeance against the assassin,\nbut with feelings of peace and gentleness, that will heal, instead of\nfestering, the wounds of our minds. Enter the house of mourning, my\nfriend, but with kindness and affection for those who love you, and not\nwith hatred for your enemies.'

In [26]:
batch02_annotations.loc[len(batch02_annotations)] = [
    60,
    0,
    "None",
    0,
    "The passage represents intense grief, guilt, and emotional suffering after William's death. Although it contains strong emotional expression, it does not demonstrate therapeutic processing, reflection, acceptance, or transformation."
]

batch02_annotations

,passage_id,therapeutic_label,mechanism,intensity,annotator_notes
0,62,1,Narrative Reconstruction,3,The passage represents emotional reflection an...
1,123,1,Narrative Reconstruction,4,The passage represents narrative reconstructio...
2,185,1,Narrative Reconstruction,3,The passage represents narrative reconstructio...
3,43,0,None,0,The passage describes Victor's obsessive scien...
4,114,1,Narrative Reconstruction,3,The passage represents narrative reconstructio...
5,153,1,Emotional Catharsis,4,The passage represents emotional catharsis thr...
6,60,0,None,0,"The passage represents intense grief, guilt, a..."

In [27]:
passage_id = 214

candidate_df[
    candidate_df["passage_id"] == passage_id
]["text"].values[0]

'His tale is connected and told with an appearance of the simplest truth,\nyet I own to you that the letters of Felix and Safie, which he showed me,\nand the apparition of the monster seen from our ship, brought to me a\ngreater conviction of the truth of his narrative than his asseverations,\nhowever earnest and connected. Such a monster has, then, really existence!\nI cannot doubt it, yet I am lost in surprise and admiration. Sometimes I\nendeavoured to gain from Frankenstein the particulars of his\ncreature’s formation, but on this point he was impenetrable. “Are you mad, my friend?” said he. “Or whither does your\nsenseless curiosity lead you? Would you also create for yourself and the\nworld a demoniacal enemy? Peace, peace! Learn my miseries and do not seek\nto increase your own.” Frankenstein discovered that I made notes concerning his history; he asked\nto see them and then himself corrected and augmented them in many places,\nbut principally in giving the life and spirit to the conversations he held\nwith his enemy. “Since you have preserved my narration,” said\nhe, “I would not that a mutilated one should go down to\nposterity.” Thus has a week passed away, while I have listened to the strangest\ntale that ever imagination formed. My thoughts and every feeling of my\nsoul have been drunk up by the interest for my guest which this tale\nand his own elevated and gentle manners have created. I wish to soothe\nhim, yet can I counsel one so infinitely miserable, so destitute of\nevery hope of consolation, to live? Oh, no! The only joy that he can\nnow know will be when he composes his shattered spirit to peace and\ndeath. Yet he enjoys one comfort, the offspring of solitude and\ndelirium; he believes that when in dreams he holds converse with his\nfriends and derives from that communion consolation for his miseries or\nexcitements to his vengeance, that they are not the creations of his\nfancy, but the beings themselves who visit him from the regions of a\nremote world. This faith gives a solemnity to his reveries that render\nthem to me almost as imposing and interesting as truth.'

In [28]:
batch02_annotations.loc[len(batch02_annotations)] = [
    214,
    1,
    "Narrative Reconstruction",
    3,
    "The passage represents narrative reconstruction through the recording, correction, and interpretation of Frankenstein's personal history. The process of organizing traumatic experiences into a coherent narrative reflects meaning-making and preservation of personal experience."
]

batch02_annotations

,passage_id,therapeutic_label,mechanism,intensity,annotator_notes
0,62,1,Narrative Reconstruction,3,The passage represents emotional reflection an...
1,123,1,Narrative Reconstruction,4,The passage represents narrative reconstructio...
2,185,1,Narrative Reconstruction,3,The passage represents narrative reconstructio...
3,43,0,None,0,The passage describes Victor's obsessive scien...
4,114,1,Narrative Reconstruction,3,The passage represents narrative reconstructio...
5,153,1,Emotional Catharsis,4,The passage represents emotional catharsis thr...
6,60,0,None,0,"The passage represents intense grief, guilt, a..."
7,214,1,Narrative Reconstruction,3,The passage represents narrative reconstructio...

In [29]:
passage_id = 222

candidate_df[
    candidate_df["passage_id"] == passage_id
]["text"].values[0]

'“Yet I cannot ask you to renounce your country and friends to fulfil\nthis task; and now that you are returning to England, you will have\nlittle chance of meeting with him. But the consideration of these\npoints, and the well balancing of what you may esteem your duties, I\nleave to you; my judgment and ideas are already disturbed by the near\napproach of death. I dare not ask you to do what I think right, for I\nmay still be misled by passion. “That he should live to be an instrument of mischief disturbs me; in\nother respects, this hour, when I momentarily expect my release, is the\nonly happy one which I have enjoyed for several years. The forms of\nthe beloved dead flit before me, and I hasten to their arms. Farewell,\nWalton! Seek happiness in tranquillity and avoid ambition, even if it\nbe only the apparently innocent one of distinguishing yourself in\nscience and discoveries. Yet why do I say this? I have myself been\nblasted in these hopes, yet another may succeed.” His voice became fainter as he spoke, and at length, exhausted by his\neffort, he sank into silence. About half an hour afterwards he\nattempted again to speak but was unable; he pressed my hand feebly, and\nhis eyes closed for ever, while the irradiation of a gentle smile passed\naway from his lips. Margaret, what comment can I make on the untimely extinction of this\nglorious spirit? What can I say that will enable you to understand the\ndepth of my sorrow? All that I should express would be inadequate and\nfeeble. My tears flow; my mind is overshadowed by a cloud of\ndisappointment. But I journey towards England, and I may there find\nconsolation.'

In [30]:
batch02_annotations.loc[len(batch02_annotations)] = [
    222,
    1,
    "Narrative Reconstruction",
    4,
    "The passage represents narrative reconstruction as Victor reflects on his life, recognizes the consequences of ambition, and transforms personal suffering into advice for Walton. The experience is reframed into moral understanding and meaning-making."
]

batch02_annotations

,passage_id,therapeutic_label,mechanism,intensity,annotator_notes
0,62,1,Narrative Reconstruction,3,The passage represents emotional reflection an...
1,123,1,Narrative Reconstruction,4,The passage represents narrative reconstructio...
2,185,1,Narrative Reconstruction,3,The passage represents narrative reconstructio...
3,43,0,None,0,The passage describes Victor's obsessive scien...
4,114,1,Narrative Reconstruction,3,The passage represents narrative reconstructio...
5,153,1,Emotional Catharsis,4,The passage represents emotional catharsis thr...
6,60,0,None,0,"The passage represents intense grief, guilt, a..."
7,214,1,Narrative Reconstruction,3,The passage represents narrative reconstructio...
8,222,1,Narrative Reconstruction,4,The passage represents narrative reconstructio...

In [31]:
passage_id = 215

candidate_df[
    candidate_df["passage_id"] == passage_id
]["text"].values[0]

'Our conversations are not always confined to his own history and\nmisfortunes. On every point of general literature he displays\nunbounded knowledge and a quick and piercing apprehension. His\neloquence is forcible and touching; nor can I hear him, when he relates\na pathetic incident or endeavours to move the passions of pity or love,\nwithout tears. What a glorious creature must he have been in the days\nof his prosperity, when he is thus noble and godlike in ruin! He seems\nto feel his own worth and the greatness of his fall. “When younger,” said he, “I believed myself destined for\nsome great enterprise. My feelings are profound, but I possessed a coolness\nof judgment that fitted me for illustrious achievements. This sentiment of\nthe worth of my nature supported me when others would have been oppressed,\nfor I deemed it criminal to throw away in useless grief those talents that\nmight be useful to my fellow creatures. When I reflected on the work I had\ncompleted, no less a one than the creation of a sensitive and rational\nanimal, I could not rank myself with the herd of common projectors. But\nthis thought, which supported me in the commencement of my career, now\nserves only to plunge me lower in the dust. All my speculations and hopes\nare as nothing, and like the archangel who aspired to omnipotence, I am\nchained in an eternal hell. My imagination was vivid, yet my powers of\nanalysis and application were intense; by the union of these qualities I\nconceived the idea and executed the creation of a man. Even now I cannot\nrecollect without passion my reveries while the work was incomplete. I trod\nheaven in my thoughts, now exulting in my powers, now burning with the idea\nof their effects. From my infancy I was imbued with high hopes and a lofty\nambition; but how am I sunk! Oh! My friend, if you had known me as I once\nwas, you would not recognise me in this state of degradation. Despondency\nrarely visited my heart; a high destiny seemed to bear me on, until I fell,\nnever, never again to rise.”'

In [32]:
batch02_annotations.loc[len(batch02_annotations)] = [
    215,
    1,
    "Narrative Reconstruction",
    4,
    "The passage represents narrative reconstruction through Victor's reflection on his former ambitions, suffering, and personal worth. His experiences are transformed into self-understanding, while emotional communication with Walton creates a meaningful interpretation of his life story."
]

batch02_annotations

,passage_id,therapeutic_label,mechanism,intensity,annotator_notes
0,62,1,Narrative Reconstruction,3,The passage represents emotional reflection an...
1,123,1,Narrative Reconstruction,4,The passage represents narrative reconstructio...
2,185,1,Narrative Reconstruction,3,The passage represents narrative reconstructio...
3,43,0,None,0,The passage describes Victor's obsessive scien...
4,114,1,Narrative Reconstruction,3,The passage represents narrative reconstructio...
5,153,1,Emotional Catharsis,4,The passage represents emotional catharsis thr...
6,60,0,None,0,"The passage represents intense grief, guilt, a..."
7,214,1,Narrative Reconstruction,3,The passage represents narrative reconstructio...
8,222,1,Narrative Reconstruction,4,The passage represents narrative reconstructio...
9,215,1,Narrative Reconstruction,4,The passage represents narrative reconstructio...

In [33]:
batch02_annotations.to_csv(
    "annotation_batch_02_completed.csv",
    index=False
)

print("Batch 02 annotations saved successfully")

Batch 02 annotations saved successfully

In [34]:
from google.colab import files

files.download("annotation_batch_02_completed.csv")

In [35]:
from google.colab import files

uploaded = files.upload()

Saving annotation_batch_02_completed.csv to annotation_batch_02_completed (1).csv

In [36]:
import pandas as pd

old_df = pd.read_csv(
    "frankenstein_training_dataset.csv"
)

batch02_df = pd.read_csv(
    "annotation_batch_02_completed.csv"
)

print("Old dataset:", len(old_df))
print("Batch 02:", len(batch02_df))

Old dataset: 29
Batch 02: 10

In [38]:
batch02_df.columns

Index(['passage_id', 'therapeutic_label', 'mechanism', 'intensity',
       'annotator_notes'],
      dtype='object')

In [39]:
# Load original passages file if not already loaded

passages_df = pd.read_csv(
    "frankenstein_passages.csv"
)

# Add text to Batch 02 annotations
batch02_df = batch02_df.merge(
    passages_df[["passage_id", "text"]],
    on="passage_id",
    how="left"
)

batch02_df.head()

,passage_id,therapeutic_label,mechanism,intensity,annotator_notes,text
0,62,1,Narrative Reconstruction,3,The passage represents emotional reflection an...,Clerval spoke thus as we hurried through the s...
1,123,1,Narrative Reconstruction,4,The passage represents narrative reconstructio...,“The volume of _Plutarch’s Lives_ which I poss...
2,185,1,Narrative Reconstruction,3,The passage represents narrative reconstructio...,"Still, as I urged our leaving Ireland with suc..."
3,43,0,NaN,0,The passage describes Victor's obsessive scien...,The summer months passed while I was thus enga...
4,114,1,Narrative Reconstruction,3,The passage represents narrative reconstructio...,“I cannot describe to you the agony that these...

In [40]:
old_df = pd.read_csv(
    "frankenstein_training_dataset.csv"
)

expanded_df = pd.concat(
    [old_df, batch02_df],
    ignore_index=True
)

print("Total annotated passages:", len(expanded_df))

Total annotated passages: 39

In [41]:
old_df = pd.read_csv(
    "frankenstein_training_dataset.csv"
)

expanded_df = pd.concat(
    [old_df, batch02_df],
    ignore_index=True
)

print("Total annotated passages:", len(expanded_df))

Total annotated passages: 39

In [42]:
expanded_df["therapeutic_label"].value_counts()

therapeutic_label
0.0    20
1.0    19
Name: count, dtype: int64

In [43]:
expanded_df["passage_id"].duplicated().sum()

np.int64(0)

In [44]:
expanded_df.to_csv(
    "frankenstein_training_dataset_v2.csv",
    index=False
)

print("Updated dataset saved successfully")

Updated dataset saved successfully

In [45]:
from google.colab import files

files.download(
    "frankenstein_training_dataset_v2.csv"
)